//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomainStyle
    {
        public int ID { get; set; }
        public int DomainID { get; set; }
        public string Favicon { get; set; }
        public string Icon { get; set; }
        public string Title { get; set; }
        public string MetaDesc { get; set; }
        public string MetaKeyword { get; set; }
        public string Maincolor { get; set; }
        public string Secondcolor { get; set; }
        public string Thirdcolor { get; set; }
    
        public virtual Domain Domain { get; set; }
    }
}
