//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomainEmail
    {
        public int ID { get; set; }
        public int DomainID { get; set; }
        public string Name { get; set; }
        public string SMTP { get; set; }
        public int Port { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string MessageAppSid { get; set; }
        public string Sender { get; set; }
        public bool UseMessages { get; set; }
    
        public virtual Domain Domain { get; set; }
    }
}
