//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAUAdmin.DTO.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class Question
    {
        public int? ID { get; set; }
        public int Index_Order { get; set; }
        public int EForm_ID { get; set; }
        public string T { get; set; }//I Input,C Check,R Radio,P Paragraph,S Spera,T Title,G Grid
        public string Name { get; set; }
        public string Name_EN { get; set; }
        public bool Requird { get; set; }
        public string Ref { get; set; }
        public Nullable<int> NRows { get; set; }

        public System.DateTime CreatedOn { get; set; }
        public bool Active { get; set; }

        public virtual ICollection<CheckBox_Type> Check { get; set; }
        public virtual E_FormsDTO E_Forms { get; set; }
        public virtual Input_Type Input { get; set; }
        public virtual ParagraphDTO Para { get; set; }
        public virtual ICollection<Radio_Type> Radio { get; set; }
        public virtual SeparatorDTO Sepa { get; set; }
        public virtual ICollection<Table_Columns> Columns { get; set; }
    }
}
