//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAUAdmin.DTO.Entity
{
	using System;
	using System.Collections.Generic;

	public partial class Question
	{
		public int ID { get; set; }
		public int EForm_ID { get; set; }
		public string Type { get; set; }
		public string LableName { get; set; }
		public string LableName_EN { get; set; }
		public bool Requird { get; set; }
		public System.DateTime CreatedOn { get; set; }
		public bool Active { get; set; }
		public virtual ICollection<CheckBox_Type> CheckBox_Type { get; set; }
		public virtual ICollection<E_Forms_Answer> E_Forms_Answer { get; set; }
		public virtual ICollection<Input_Type> Input_Type { get; set; }
		public virtual ICollection<Radio_Type> Radio_Type { get; set; }
		public virtual E_FormsDTO E_Forms { get; set; }
	}
}
