//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MustafidApp.Helpers.SaveRequest
{
    using System;
    using System.Collections.Generic;

    public partial class SaveReq_E_Forms_Answer
    {
        public int? ID { get; set; }
        public int? Person_ID { get; set; }
        public int? Question_ID { get; set; }
        public int? EFromID { get; set; }
        public string Value_En { get; set; }
        public string T { get; set; }
        public string Value { get; set; }
        public string Name { get; set; }
        public string Name_En { get; set; }
        public System.DateTime? FillDate { get; set; }
        public ICollection<SaveReq_Preview_TableCols> Preview_TableCols { get; set; }
    }
}
