//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAUBackEnd.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Purchase_Order_Form = new HashSet<Purchase_Order_Form>();
        }
    
        public int Department_ID { get; set; }
        public string Department_Name_AR { get; set; }
        public string Department_Name_EN { get; set; }
        public Nullable<int> College_Administration_ID { get; set; }
        public Nullable<bool> IS_Action { get; set; }
    
        public virtual College_Administration College_Administration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Order_Form> Purchase_Order_Form { get; set; }
    }
}
