//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAUBackEnd.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eform_Approval
    {
        public int ID { get; set; }
        public int UnitID { get; set; }
        public int EformID { get; set; }
    
        public virtual E_Forms E_Forms { get; set; }
        public virtual Units Units { get; set; }
    }
}
