//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAUBackEnd.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preview_EformApproval
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Name_En { get; set; }
        public Nullable<int> UnitID { get; set; }
        public bool OwnEform { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public int PersonEform { get; set; }
    
        public virtual Person_Eform Person_Eform { get; set; }
        public virtual Units Units { get; set; }
    }
}
