//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAUBackEnd.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Order_Form_Required
    {
        public int Purchase_Order_Form_Required_ID { get; set; }
        public string Required_Specifications_Name { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<int> Purchase_Order_Form_ID { get; set; }
        public Nullable<bool> IS_Action { get; set; }
    
        public virtual Purchase_Order_Form Purchase_Order_Form { get; set; }
    }
}
