//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAUBackEnd.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestTransaction
    {
        public int ID { get; set; }
        public int Request_ID { get; set; }
        public int FromUnitID { get; set; }
        public Nullable<int> ToUnitID { get; set; }
        public Nullable<System.DateTime> ForwardDate { get; set; }
        public Nullable<System.DateTime> ExpireDays { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CommentType { get; set; }
        public bool Readed { get; set; }
        public Nullable<System.DateTime> ReadedDate { get; set; }
        public string MostafidComment { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public string Code { get; set; }
        public bool Is_Reminder { get; set; }
    
        public virtual Request_Data Request_Data { get; set; }
        public virtual Units Units { get; set; }
        public virtual Units Units1 { get; set; }
    }
}
