//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applicant_Type()
        {
            this.Personel_Data = new HashSet<Personel_Data>();
            this.ValidTo = new HashSet<ValidTo>();
        }
    
        public int Applicant_Type_ID { get; set; }
        public string Applicant_Type_Name_EN { get; set; }
        public string Applicant_Type_Name_AR { get; set; }
        public Nullable<bool> IS_Action { get; set; }
        public bool Affliated { get; set; }
        public int Index { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personel_Data> Personel_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValidTo> ValidTo { get; set; }
    }
}
