//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelayedTransaction
    {
        public int ID { get; set; }
        public int RequestID { get; set; }
        public string RequestCode { get; set; }
        public byte RequestStatus { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int Delayed { get; set; }
        public System.DateTime AddedDate { get; set; }
        public bool Readed { get; set; }
    
        public virtual Request_Data Request_Data { get; set; }
        public virtual Request_State Request_State { get; set; }
    }
}
