//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Forms_Answer
    {
        public int ID { get; set; }
        public Nullable<int> Question_ID { get; set; }
        public Nullable<int> EForm_ID { get; set; }
        public string Value { get; set; }
        public string Value_En { get; set; }
        public Nullable<System.DateTime> FillDate { get; set; }
        public string Name { get; set; }
        public string Name_En { get; set; }
        public string Type { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
