//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Forms_Answer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public E_Forms_Answer()
        {
            this.Preview_TableCols = new HashSet<Preview_TableCols>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Question_ID { get; set; }
        public Nullable<int> EForm_ID { get; set; }
        public string Value { get; set; }
        public string Value_En { get; set; }
        public Nullable<System.DateTime> FillDate { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Name_En { get; set; }
    
        public virtual Person_Eform Person_Eform { get; set; }
        public virtual Question Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preview_TableCols> Preview_TableCols { get; set; }
    }
}
