//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Main_Services()
        {
            this.Sub_Services = new HashSet<Sub_Services>();
            this.UnitMainServices = new HashSet<UnitMainServices>();
            this.ValidTo = new HashSet<ValidTo>();
        }
    
        public int Main_Services_ID { get; set; }
        public string Main_Services_Name_EN { get; set; }
        public string Main_Services_Name_AR { get; set; }
        public Nullable<bool> IS_Action { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
    
        public virtual Service_Type Service_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sub_Services> Sub_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitMainServices> UnitMainServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValidTo> ValidTo { get; set; }
    }
}
