//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel_Data()
        {
            this.Person_Eform = new HashSet<Person_Eform>();
            this.Request_Data = new HashSet<Request_Data>();
        }
    
        public int Personel_Data_ID { get; set; }
        public string IAU_ID_Number { get; set; }
        public Nullable<int> Applicant_Type_ID { get; set; }
        public Nullable<int> Title_Middle_Names_ID { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> Nationality_ID { get; set; }
        public int ID_Document { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public string ID_Number { get; set; }
        public int Address_CountryID { get; set; }
        public Nullable<int> Address_CityID { get; set; }
        public Nullable<int> Adress_RegionID { get; set; }
        public string Address_City { get; set; }
        public string Adress_Region { get; set; }
        public string Postal_Code { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string IS_Action { get; set; }
    
        public virtual Applicant_Type Applicant_Type { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Country Country2 { get; set; }
        public virtual ID_Document ID_Document1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_Eform> Person_Eform { get; set; }
        public virtual Region Region { get; set; }
        public virtual Title_Middle_Names Title_Middle_Names { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Data> Request_Data { get; set; }
    }
}
