//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumberNotification
    {
        public int ID { get; set; }
        public string PhoneNumber { get; set; }
        public string Message { get; set; }
        public string Message_EN { get; set; }
        public Nullable<int> RequestID { get; set; }
        public System.DateTime NotiDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public bool Readed { get; set; }
    
        public virtual Request_Data Request_Data { get; set; }
        public virtual Users Users { get; set; }
    }
}
