//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preview_TableCols
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preview_TableCols()
        {
            this.Tables_Answare = new HashSet<Tables_Answare>();
        }
    
        public int ID { get; set; }
        public int EFormAnswareID { get; set; }
        public string Name { get; set; }
        public string Name_En { get; set; }
    
        public virtual E_Forms_Answer E_Forms_Answer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tables_Answare> Tables_Answare { get; set; }
    }
}
