//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Privilage()
        {
            this.Job_Permissions = new HashSet<Job_Permissions>();
            this.Privilage1 = new HashSet<Privilage>();
            this.Privilage11 = new HashSet<Privilage>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Name_EN { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> SubOF { get; set; }
        public Nullable<int> DetailedFrom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_Permissions> Job_Permissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Privilage> Privilage1 { get; set; }
        public virtual Privilage Privilage2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Privilage> Privilage11 { get; set; }
        public virtual Privilage Privilage3 { get; set; }
    }
}
