//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Order_Form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase_Order_Form()
        {
            this.Purchase_Order_Form_Required = new HashSet<Purchase_Order_Form_Required>();
        }
    
        public int Purchase_Order_Form_ID { get; set; }
        public Nullable<int> Type_Support_Project_ID { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public Nullable<System.DateTime> Purchase_Order_Form_Date { get; set; }
        public Nullable<int> Supplier_Names_ID_1 { get; set; }
        public Nullable<int> Supplier_Names_ID_2 { get; set; }
        public Nullable<int> Supplier_Names_ID_3 { get; set; }
        public Nullable<bool> IS_Action { get; set; }
        public string Research_Project_Need_No { get; set; }
        public string Distracted_From_Item { get; set; }
        public string Name_Principal_Researcher { get; set; }
        public string Job_Title { get; set; }
        public string College { get; set; }
        public string Justifications_Signature { get; set; }
        public string Mobile_Finder { get; set; }
        public string Supervisor_Name { get; set; }
        public string Supervisor_Signature { get; set; }
        public Nullable<int> FollowUp_Publication_Violations_ID { get; set; }
        public string FollowUp_Publication_Violations_Name { get; set; }
        public string FollowUp_Publication_Violations_Signature { get; set; }
        public Nullable<System.DateTime> FollowUp_Publication_Violations_Date { get; set; }
        public Nullable<int> Event_Publication_Violation_ID { get; set; }
        public string Event_Publication_Violation_Name { get; set; }
        public string Event_Publication_Violation_Signature { get; set; }
        public Nullable<System.DateTime> Event_Publication_Violation_Date { get; set; }
        public string Name_Warehouse_Keeper_Name { get; set; }
        public string Name_Warehouse_Keeper_Signature { get; set; }
        public Nullable<System.DateTime> Name_Warehouse_Keeper_Date { get; set; }
        public Nullable<int> Authority_Holder_ID { get; set; }
        public string Authority_Holder_Name { get; set; }
        public string Authority_Holder_Signature { get; set; }
        public Nullable<System.DateTime> Authority_Holder_Date { get; set; }
        public Nullable<int> Statement_Department_File_Sent_Them_ID { get; set; }
        public string Statement_Department_File_Sent_Them_Responsible_Name { get; set; }
        public string Statement_Department_File_Sent_Them_Signature { get; set; }
        public Nullable<System.DateTime> Statement_Department_File_Sent_Them_Date { get; set; }
        public Nullable<int> Engagements_Department_ID { get; set; }
        public string Engagements_Department_Price { get; set; }
        public string Engagements_Department_Item_No1 { get; set; }
        public string Engagements_Department_Link_Number { get; set; }
        public string Engagements_Department_Competent_Employee { get; set; }
        public string Engagements_Department_Competent_Signature { get; set; }
        public Nullable<System.DateTime> Engagements_Department_Competent_Date { get; set; }
    
        public virtual Authority_Holder Authority_Holder { get; set; }
        public virtual Department Department { get; set; }
        public virtual Engagements_Department Engagements_Department { get; set; }
        public virtual Event_Publication_Violation Event_Publication_Violation { get; set; }
        public virtual FollowUp_Publication_Violations FollowUp_Publication_Violations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Order_Form_Required> Purchase_Order_Form_Required { get; set; }
        public virtual Supplier_Names Supplier_Names { get; set; }
        public virtual Type_Support_Project Type_Support_Project { get; set; }
    }
}
