//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.CheckBox_Type = new HashSet<CheckBox_Type>();
            this.E_Forms_Answer = new HashSet<E_Forms_Answer>();
            this.Radio_Type = new HashSet<Radio_Type>();
        }
    
        public int ID { get; set; }
        public int Index_Order { get; set; }
        public int EForm_ID { get; set; }
        public string Type { get; set; }
        public string LableName { get; set; }
        public string LableName_EN { get; set; }
        public bool Requird { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string RefTo { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckBox_Type> CheckBox_Type { get; set; }
        public virtual E_Forms E_Forms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<E_Forms_Answer> E_Forms_Answer { get; set; }
        public virtual Input_Type Input_Type { get; set; }
        public virtual Paragraph Paragraph { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Radio_Type> Radio_Type { get; set; }
        public virtual Separator Separator { get; set; }
    }
}
