//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Log
    {
        public byte Request_State_ID { get; set; }
        public int ID { get; set; }
        public int Request_ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> Employee_ID { get; set; }
    
        public virtual Request_Data Request_Data { get; set; }
        public virtual Request_State Request_State { get; set; }
    }
}
