//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statement_Department_File_Sent_Them
    {
        public int Statement_Department_File_Sent_Them_ID { get; set; }
        public string Statement_Department_File_Sent_Them_Name_AR { get; set; }
        public string Statement_Department_File_Sent_Them_Name_EN { get; set; }
    }
}
