//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubDomains
    {
        public int ID { get; set; }
        public int DomainID { get; set; }
        public string Key { get; set; }
        public string Domain { get; set; }
        public bool UseHttps { get; set; }
    
        public virtual Domain Domain1 { get; set; }
    }
}
