//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Method { get; set; }
        public System.DateTime TransDate { get; set; }
        public int ClassType { get; set; }
        public string Oldval { get; set; }
        public string Newval { get; set; }
        public string CallPath { get; set; }
    }
}
