//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tables_Answare
    {
        public int ID { get; set; }
        public int Row { get; set; }
        public int Column { get; set; }
        public string Value { get; set; }
    
        public virtual Preview_TableCols Preview_TableCols { get; set; }
    }
}
