//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string User_Mobile { get; set; }
        public string User_Email { get; set; }
        public string User_Password { get; set; }
        public Nullable<int> User_Permissions_Type_ID { get; set; }
        public Nullable<int> User_Active_ID { get; set; }
    
        public virtual User_Active User_Active { get; set; }
        public virtual User_Permissions_Type User_Permissions_Type { get; set; }
    }
}
