//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Permissions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Permissions()
        {
            this.User_Permissions1 = new HashSet<User_Permissions>();
        }
    
        public int User_Permissions_ID { get; set; }
        public string User_Permissions_Name_AR { get; set; }
        public string User_Permissions_Name_EN { get; set; }
        public Nullable<int> User_Permissions_Type_ID { get; set; }
        public Nullable<int> SubPageOF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Permissions> User_Permissions1 { get; set; }
        public virtual User_Permissions User_Permissions2 { get; set; }
        public virtual User_Permissions_Type User_Permissions_Type { get; set; }
    }
}
