//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAU_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidTo
    {
        public int ID { get; set; }
        public int MainServiceID { get; set; }
        public int ApplicantTypeID { get; set; }
    
        public virtual Applicant_Type Applicant_Type { get; set; }
        public virtual Main_Services Main_Services { get; set; }
    }
}
